_core:
  default_config_hash: RMy8ch2MOT68bCD63OGZQRdMk2pD6UXPEZMuCIisbfs
langcode: en
activate: true
auth_source: default-sp
login_link_display_name: 'Log in with your SLAC ID'
login_link_show: true
user_name: uid
unique_id: uid
mail_attr: mail
header_no_cache: true
role:
  population: 'content_editor:eduPersonEntitlement,=,http://slac.stanford.edu/drupal/Editor|author:eduPersonEntitlement,=,http://slac.stanford.edu/drupal/Author|reviewer:eduPersonEntitlement,=,http://slac.stanford.edu/drupal/Reviewer|manager:eduPersonEntitlement,=,http://slac.stanford.edu/drupal/Manager|administrator:eduPersonEntitlement,=,http://slac.stanford.edu/drupal/Administrator'
  eval_every_time: true
register_users: true
allow:
  set_drupal_pwd: false
  default_login: true
  default_login_roles:
    administrator: administrator
  default_login_users: '1'
logout_goto_url: /
user_register_original: visitors_admin_approval
sync:
  mail: true
  user_name: true
autoenablesaml: true
debug: true
secure: true
httponly: false
